name: Docker Image CI

on:
  push:
    branches:
      - main
    paths:
      - 'versions.env'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: k9s-web
  REPO_OWNER: lordmathis
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  build:
  
    permissions:
      packages: write
      contents: write
      pull-requests: read
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

    - uses: rymndhng/release-on-push-action@master
      id: release
      with:
        bump_version_scheme: minor
        use_github_release_notes: true

    - name: Set build args env
      run: |
        set -a
        source versions.env
        set +a
        echo TTYD_VERSION=$TTYD_VERSION >>${GITHUB_ENV}
        echo K9S_VERSION=$K9S_VERSION >>${GITHUB_ENV}

    - name: Log in to the Container registry
      uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@cfed4e995e12d7bee5002f066f5649e5f1cc059c
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.IMAGE_NAME }}:${{ steps.release.outputs.tag_name }}
          ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ env.IMAGE_NAME }}:latest
        addLatest: true
        build-args: |
          TTYD_VERSION=${{ env.TTYD_VERSION }}
          K9S_VERSION=${{ env.K9S_VERSION }}