name: Renovate Bot Github Action

on:
  push:
    branches: [ "main" ]

jobs:
  renovate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Renovate Bot GitHub Action
      uses: renovatebot/github-action@v40.1.11
